---

env:
  browser: true
  commonjs: true
  es6: true
  jquery: true

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  no-case-declarations: 0
  no-underscore-dangle: 0
  no-restricted-globals: 0